using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using PhoneApp.Domain;
using PhoneApp.Domain.Attributes;
using PhoneApp.Domain.DTO;
using PhoneApp.Domain.Interfaces;
namespace EmployeesLoaderPlugin
{

    [Author(Name = "Pavel Novopashin")]
    public class Plugin : IPluggable
    {
        private static readonly NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
        public IEnumerable<DataTransferObject> Run(IEnumerable<DataTransferObject> args)
        {
            logger.Info("Starting NewPlugin This is NewPlugin");
            logger.Info("Type q to exit");
            logger.Info("Available commands: list, add, del \r\n" +
                "l2 - print json saved in program: 'employeesList2',\r\n" +
                "d2 - delete element of: 'employeesList2', \r\n" +
                "a2 - add new element in: 'employeesList2' \r\n" +
                "l3 - print file: 'dataJson.json'  \r\n" +
                "d3 - delete element of 'dataJson.json' \r\n" +
                "l4 - print json contains of 1 element: 'json.txt' \r\n" +
                "f - загрузка всех файлов .json \r\n" +
                "fl - печать пользователей загруженных всех файлов .json \r\n" +
                "fd - удалить элемент загруженных пользователей файлов .json\r\n" +
                "fa - добавить нового пользователя к загруженным пользователям файлов .json");

            var employeesList = args.Cast<EmployeesDTO>().ToList();
            var fileJson0 = "[\r\n    {\r\n      \"id\": 1,\r\n      \"Name\": \"Emily\",\r\n      \"lastName\": \"Johnson\",\r\n      \"maidenName\": \"Smith\",\r\n      \"age\": 28,\r\n      \"gender\": \"female\",\r\n      \"email\": \"emily.johnson@x.dummyjson.com\",\r\n      \"phone\": \"+81 965-431-3024\",\r\n      \"username\": \"emilys\",\r\n      \"password\": \"emilyspass\",\r\n      \"birthDate\": \"1996-5-30\",\r\n      \"image\": \"https://dummyjson.com/icon/emilys/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 193.24,\r\n      \"weight\": 63.16,\r\n      \"eyeColor\": \"Green\",\r\n      \"hair\": {\r\n        \"color\": \"Brown\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"42.48.100.32\",\r\n      \"address\": {\r\n        \"address\": \"626 Main Street\",\r\n        \"city\": \"Phoenix\",\r\n        \"state\": \"Mississippi\",\r\n        \"stateCode\": \"MS\",\r\n        \"postalCode\": \"29112\",\r\n        \"coordinates\": {\r\n          \"lat\": -77.16213,\r\n          \"lng\": -92.084824\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"47:fa:41:18:ec:eb\",\r\n      \"university\": \"University of Wisconsin--Madison\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"03/26\",\r\n        \"cardNumber\": \"9289760655481815\",\r\n        \"cardType\": \"Elo\",\r\n        \"currency\": \"CNY\",\r\n        \"iban\": \"YPUXISOBI7TTHPK2BR3HAIXL\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Engineering\",\r\n        \"name\": \"Dooley, Kozey and Cronin\",\r\n        \"title\": \"Sales Manager\",\r\n        \"address\": {\r\n          \"address\": \"263 Tenth Street\",\r\n          \"city\": \"San Francisco\",\r\n          \"state\": \"Wisconsin\",\r\n          \"stateCode\": \"WI\",\r\n          \"postalCode\": \"37657\",\r\n          \"coordinates\": {\r\n            \"lat\": 71.814525,\r\n            \"lng\": -161.150263\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"977-175\",\r\n      \"ssn\": \"900-590-289\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    },\r\n " +
                "   {\r\n      \"id\": 2,\r\n      \"Name\": \"Michael\",\r\n      \"lastName\": \"Williams\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 35,\r\n      \"gender\": \"male\",\r\n      \"email\": \"michael.williams@x.dummyjson.com\",\r\n      \"phone\": \"+49 258-627-6644\",\r\n      \"username\": \"michaelw\",\r\n      \"password\": \"michaelwpass\",\r\n      \"birthDate\": \"1989-8-10\",\r\n      \"image\": \"https://dummyjson.com/icon/michaelw/128\",\r\n      \"bloodGroup\": \"B+\",\r\n      \"height\": 186.22,\r\n      \"weight\": 76.32,\r\n      \"eyeColor\": \"Red\",\r\n      \"hair\": {\r\n        \"color\": \"Green\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"12.13.116.142\",\r\n      \"address\": {\r\n        \"address\": \"385 Fifth Street\",\r\n        \"city\": \"Houston\",\r\n        \"state\": \"Alabama\",\r\n        \"stateCode\": \"AL\",\r\n        \"postalCode\": \"38807\",\r\n        \"coordinates\": {\r\n          \"lat\": 22.815468,\r\n          \"lng\": 115.608581\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"79:15:78:99:60:aa\",\r\n      \"university\": \"Ohio State University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"02/27\",\r\n        \"cardNumber\": \"6737807858721625\",\r\n        \"cardType\": \"Elo\",\r\n        \"currency\": \"SEK\",\r\n        \"iban\": \"83IDT77FWYLCJVR8ISDACFH0\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Support\",\r\n        \"name\": \"Spinka - Dickinson\",\r\n        \"title\": \"Support Specialist\",\r\n        \"address\": {\r\n          \"address\": \"395 Main Street\",\r\n          \"city\": \"Los Angeles\",\r\n          \"state\": \"New Hampshire\",\r\n          \"stateCode\": \"NH\",\r\n          \"postalCode\": \"73442\",\r\n          \"coordinates\": {\r\n            \"lat\": 79.098326,\r\n            \"lng\": -119.624845\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"912-602\",\r\n      \"ssn\": \"108-953-962\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    }]";
            var fileJson1 = "[\r\n    {\r\n      \"id\": 1,\r\n      \"Name\": \"EmilyfileJson1\",\r\n      \"lastName\": \"Johnson\",\r\n      \"maidenName\": \"Smith\",\r\n      \"age\": 28,\r\n      \"gender\": \"female\",\r\n      \"email\": \"emily.johnson@x.dummyjson.com\",\r\n      \"Phone\": \"+81 965-431-3024\",\r\n      \"username\": \"emilys\",\r\n      \"password\": \"emilyspass\",\r\n      \"birthDate\": \"1996-5-30\",\r\n      \"image\": \"https://dummyjson.com/icon/emilys/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 193.24,\r\n      \"weight\": 63.16,\r\n      \"eyeColor\": \"Green\",\r\n      \"hair\": {\r\n        \"color\": \"Brown\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"42.48.100.32\",\r\n      \"address\": {\r\n        \"address\": \"626 Main Street\",\r\n        \"city\": \"Phoenix\",\r\n        \"state\": \"Mississippi\",\r\n        \"stateCode\": \"MS\",\r\n        \"postalCode\": \"29112\",\r\n        \"coordinates\": {\r\n          \"lat\": -77.16213,\r\n          \"lng\": -92.084824\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"47:fa:41:18:ec:eb\",\r\n      \"university\": \"University of Wisconsin--Madison\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"03/26\",\r\n        \"cardNumber\": \"9289760655481815\",\r\n        \"cardType\": \"Elo\",\r\n        \"currency\": \"CNY\",\r\n        \"iban\": \"YPUXISOBI7TTHPK2BR3HAIXL\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Engineering\",\r\n        \"name\": \"Dooley, Kozey and Cronin\",\r\n        \"title\": \"Sales Manager\",\r\n        \"address\": {\r\n          \"address\": \"263 Tenth Street\",\r\n          \"city\": \"San Francisco\",\r\n          \"state\": \"Wisconsin\",\r\n          \"stateCode\": \"WI\",\r\n          \"postalCode\": \"37657\",\r\n          \"coordinates\": {\r\n            \"lat\": 71.814525,\r\n            \"lng\": -161.150263\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"977-175\",\r\n      \"ssn\": \"900-590-289\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 2,\r\n      \"Name\": \"Michael\",\r\n      \"lastName\": \"Williams\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 35,\r\n      \"gender\": \"male\",\r\n      \"email\": \"michael.williams@x.dummyjson.com\",\r\n      \"phone\": \"+49 258-627-6644\",\r\n      \"username\": \"michaelw\",\r\n      \"password\": \"michaelwpass\",\r\n      \"birthDate\": \"1989-8-10\",\r\n      \"image\": \"https://dummyjson.com/icon/michaelw/128\",\r\n      \"bloodGroup\": \"B+\",\r\n      \"height\": 186.22,\r\n      \"weight\": 76.32,\r\n      \"eyeColor\": \"Red\",\r\n      \"hair\": {\r\n        \"color\": \"Green\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"12.13.116.142\",\r\n      \"address\": {\r\n        \"address\": \"385 Fifth Street\",\r\n        \"city\": \"Houston\",\r\n        \"state\": \"Alabama\",\r\n        \"stateCode\": \"AL\",\r\n        \"postalCode\": \"38807\",\r\n        \"coordinates\": {\r\n          \"lat\": 22.815468,\r\n          \"lng\": 115.608581\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"79:15:78:99:60:aa\",\r\n      \"university\": \"Ohio State University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"02/27\",\r\n        \"cardNumber\": \"6737807858721625\",\r\n        \"cardType\": \"Elo\",\r\n        \"currency\": \"SEK\",\r\n        \"iban\": \"83IDT77FWYLCJVR8ISDACFH0\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Support\",\r\n        \"name\": \"Spinka - Dickinson\",\r\n        \"title\": \"Support Specialist\",\r\n        \"address\": {\r\n          \"address\": \"395 Main Street\",\r\n          \"city\": \"Los Angeles\",\r\n          \"state\": \"New Hampshire\",\r\n          \"stateCode\": \"NH\",\r\n          \"postalCode\": \"73442\",\r\n          \"coordinates\": {\r\n            \"lat\": 79.098326,\r\n            \"lng\": -119.624845\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"912-602\",\r\n      \"ssn\": \"108-953-962\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 3,\r\n      \"Name\": \"Sophia\",\r\n      \"lastName\": \"Brown\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 42,\r\n      \"gender\": \"female\",\r\n      \"email\": \"sophia.brown@x.dummyjson.com\",\r\n      \"phone\": \"+81 210-652-2785\",\r\n      \"username\": \"sophiab\",\r\n      \"password\": \"sophiabpass\",\r\n      \"birthDate\": \"1982-11-6\",\r\n      \"image\": \"https://dummyjson.com/icon/sophiab/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 177.72,\r\n      \"weight\": 52.6,\r\n      \"eyeColor\": \"Hazel\",\r\n      \"hair\": {\r\n        \"color\": \"White\",\r\n        \"type\": \"Wavy\"\r\n      },\r\n      \"ip\": \"214.225.51.195\",\r\n      \"address\": {\r\n        \"address\": \"1642 Ninth Street\",\r\n        \"city\": \"Washington\",\r\n        \"state\": \"Alabama\",\r\n        \"stateCode\": \"AL\",\r\n        \"postalCode\": \"32822\",\r\n        \"coordinates\": {\r\n          \"lat\": 45.289366,\r\n          \"lng\": 46.832664\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"12:a3:d3:6f:5c:5b\",\r\n      \"university\": \"Pepperdine University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"04/25\",\r\n        \"cardNumber\": \"7795895470082859\",\r\n        \"cardType\": \"Korean Express\",\r\n        \"currency\": \"SEK\",\r\n        \"iban\": \"90XYKT83LMM7AARZ8JN958JC\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Research and Development\",\r\n        \"name\": \"Schiller - Zieme\",\r\n        \"title\": \"Accountant\",\r\n        \"address\": {\r\n          \"address\": \"1896 Washington Street\",\r\n          \"city\": \"Dallas\",\r\n          \"state\": \"Nevada\",\r\n          \"stateCode\": \"NV\",\r\n          \"postalCode\": \"88511\",\r\n          \"coordinates\": {\r\n            \"lat\": 20.086743,\r\n            \"lng\": -34.577107\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"963-113\",\r\n      \"ssn\": \"638-461-822\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 4,\r\n      \"firstName\": \"James\",\r\n      \"lastName\": \"Davis\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 45,\r\n      \"gender\": \"male\",\r\n      \"email\": \"james.davis@x.dummyjson.com\",\r\n      \"phone\": \"+49 614-958-9364\",\r\n      \"username\": \"jamesd\",\r\n      \"password\": \"jamesdpass\",\r\n      \"birthDate\": \"1979-5-4\",\r\n      \"image\": \"https://dummyjson.com/icon/jamesd/128\",\r\n      \"bloodGroup\": \"AB+\",\r\n      \"height\": 193.31,\r\n      \"weight\": 62.1,\r\n      \"eyeColor\": \"Amber\",\r\n      \"hair\": {\r\n        \"color\": \"Blonde\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"101.118.131.66\",\r\n      \"address\": {\r\n        \"address\": \"238 Jefferson Street\",\r\n        \"city\": \"Seattle\",\r\n        \"state\": \"Pennsylvania\",\r\n        \"stateCode\": \"PA\",\r\n        \"postalCode\": \"68354\",\r\n        \"coordinates\": {\r\n          \"lat\": 16.782513,\r\n          \"lng\": -139.34723\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"10:7d:df:1f:97:58\",\r\n      \"university\": \"University of Southern California\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/29\",\r\n        \"cardNumber\": \"5005519846254763\",\r\n        \"cardType\": \"Mastercard\",\r\n        \"currency\": \"INR\",\r\n        \"iban\": \"7N7ZH1PJ8Q4WU1K965HQQR27\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Support\",\r\n        \"name\": \"Pagac and Sons\",\r\n        \"title\": \"Research Analyst\",\r\n        \"address\": {\r\n          \"address\": \"1622 Lincoln Street\",\r\n          \"city\": \"Fort Worth\",\r\n          \"state\": \"Pennsylvania\",\r\n          \"stateCode\": \"PA\",\r\n          \"postalCode\": \"27768\",\r\n          \"coordinates\": {\r\n            \"lat\": 54.91193,\r\n            \"lng\": -79.498328\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"904-810\",\r\n      \"ssn\": \"116-951-314\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 5,\r\n      \"Name\": \"Emma\",\r\n      \"lastName\": \"Miller\",\r\n      \"maidenName\": \"Johnson\",\r\n      \"age\": 30,\r\n      \"gender\": \"female\",\r\n      \"email\": \"emma.miller@x.dummyjson.com\",\r\n      \"phone\": \"+91 759-776-1614\",\r\n      \"username\": \"emmaj\",\r\n      \"password\": \"emmajpass\",\r\n      \"birthDate\": \"1994-6-13\",\r\n      \"image\": \"https://dummyjson.com/icon/emmaj/128\",\r\n      \"bloodGroup\": \"AB-\",\r\n      \"height\": 192.8,\r\n      \"weight\": 63.62,\r\n      \"eyeColor\": \"Green\",\r\n      \"hair\": {\r\n        \"color\": \"White\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"224.126.22.183\",\r\n      \"address\": {\r\n        \"address\": \"607 Fourth Street\",\r\n        \"city\": \"Jacksonville\",\r\n        \"state\": \"Colorado\",\r\n        \"stateCode\": \"CO\",\r\n        \"postalCode\": \"26593\",\r\n        \"coordinates\": {\r\n          \"lat\": 0.505589,\r\n          \"lng\": -157.43281\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"32:b9:7e:8d:f5:e8\",\r\n      \"university\": \"Northeastern University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"03/26\",\r\n        \"cardNumber\": \"5772950119588627\",\r\n        \"cardType\": \"American Express\",\r\n        \"currency\": \"CAD\",\r\n        \"iban\": \"TAVHURD845KVBTB8W81AQXRY\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Human Resources\",\r\n        \"name\": \"Graham - Gulgowski\",\r\n        \"title\": \"Quality Assurance Engineer\",\r\n        \"address\": {\r\n          \"address\": \"1460 Sixth Street\",\r\n          \"city\": \"San Antonio\",\r\n          \"state\": \"Idaho\",\r\n          \"stateCode\": \"ID\",\r\n          \"postalCode\": \"21965\",\r\n          \"coordinates\": {\r\n            \"lat\": 44.346545,\r\n            \"lng\": -26.944701\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"403-505\",\r\n      \"ssn\": \"526-210-885\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 6,\r\n      \"Name\": \"Olivia\",\r\n      \"lastName\": \"Wilson\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 22,\r\n      \"gender\": \"female\",\r\n      \"email\": \"olivia.wilson@x.dummyjson.com\",\r\n      \"phone\": \"+91 607-295-6448\",\r\n      \"username\": \"oliviaw\",\r\n      \"password\": \"oliviawpass\",\r\n      \"birthDate\": \"2002-4-20\",\r\n      \"image\": \"https://dummyjson.com/icon/oliviaw/128\",\r\n      \"bloodGroup\": \"B+\",\r\n      \"height\": 182.61,\r\n      \"weight\": 58,\r\n      \"eyeColor\": \"Hazel\",\r\n      \"hair\": {\r\n        \"color\": \"Gray\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"249.178.112.207\",\r\n      \"address\": {\r\n        \"address\": \"547 First Street\",\r\n        \"city\": \"Fort Worth\",\r\n        \"state\": \"Tennessee\",\r\n        \"stateCode\": \"TN\",\r\n        \"postalCode\": \"83843\",\r\n        \"coordinates\": {\r\n          \"lat\": 75.32627,\r\n          \"lng\": -26.15285\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"9c:7f:ea:34:18:19\",\r\n      \"university\": \"University of North Carolina--Chapel Hill\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/28\",\r\n        \"cardNumber\": \"6771923832947881\",\r\n        \"cardType\": \"Diners Club International\",\r\n        \"currency\": \"BRL\",\r\n        \"iban\": \"V6H0O5OE3Q4JVKWDTYWZABMD\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Product Management\",\r\n        \"name\": \"Pfannerstill Inc\",\r\n        \"title\": \"Research Analyst\",\r\n        \"address\": {\r\n          \"address\": \"425 Sixth Street\",\r\n          \"city\": \"Indianapolis\",\r\n          \"state\": \"Oklahoma\",\r\n          \"stateCode\": \"OK\",\r\n          \"postalCode\": \"74263\",\r\n          \"coordinates\": {\r\n            \"lat\": 74.986644,\r\n            \"lng\": -132.916888\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"921-709\",\r\n      \"ssn\": \"836-772-168\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 7,\r\n      \"Name\": \"Alexander\",\r\n      \"lastName\": \"Jones\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 38,\r\n      \"gender\": \"male\",\r\n      \"email\": \"alexander.jones@x.dummyjson.com\",\r\n      \"phone\": \"+61 260-824-4986\",\r\n      \"username\": \"alexanderj\",\r\n      \"password\": \"alexanderjpass\",\r\n      \"birthDate\": \"1986-10-20\",\r\n      \"image\": \"https://dummyjson.com/icon/alexanderj/128\",\r\n      \"bloodGroup\": \"AB-\",\r\n      \"height\": 153.89,\r\n      \"weight\": 77.42,\r\n      \"eyeColor\": \"Blue\",\r\n      \"hair\": {\r\n        \"color\": \"White\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"166.204.84.32\",\r\n      \"address\": {\r\n        \"address\": \"664 Maple Street\",\r\n        \"city\": \"Indianapolis\",\r\n        \"state\": \"Delaware\",\r\n        \"stateCode\": \"DE\",\r\n        \"postalCode\": \"86684\",\r\n        \"coordinates\": {\r\n          \"lat\": 35.289664,\r\n          \"lng\": 7.063255\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"d2:64:58:2d:1c:46\",\r\n      \"university\": \"University of Illinois--Urbana-Champaign\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/25\",\r\n        \"cardNumber\": \"7344951706130140\",\r\n        \"cardType\": \"JCB\",\r\n        \"currency\": \"EUR\",\r\n        \"iban\": \"49V4GVDVMP0MHIDD4VXMQ3A2\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Engineering\",\r\n        \"name\": \"Dickens - Beahan\",\r\n        \"title\": \"Web Developer\",\r\n        \"address\": {\r\n          \"address\": \"996 Eighth Street\",\r\n          \"city\": \"Washington\",\r\n          \"state\": \"Kansas\",\r\n          \"stateCode\": \"KS\",\r\n          \"postalCode\": \"27858\",\r\n          \"coordinates\": {\r\n            \"lat\": -75.462366,\r\n            \"lng\": -128.025697\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"638-127\",\r\n      \"ssn\": \"722-993-925\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 8,\r\n      \"Name\": \"Ava\",\r\n      \"lastName\": \"Taylor\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 27,\r\n      \"gender\": \"female\",\r\n      \"email\": \"ava.taylor@x.dummyjson.com\",\r\n      \"phone\": \"+1 458-853-7877\",\r\n      \"username\": \"avat\",\r\n      \"password\": \"avatpass\",\r\n      \"birthDate\": \"1997-8-25\",\r\n      \"image\": \"https://dummyjson.com/icon/avat/128\",\r\n      \"bloodGroup\": \"AB-\",\r\n      \"height\": 168.47,\r\n      \"weight\": 57.08,\r\n      \"eyeColor\": \"Hazel\",\r\n      \"hair\": {\r\n        \"color\": \"Red\",\r\n        \"type\": \"Kinky\"\r\n      },\r\n      \"ip\": \"150.73.197.233\",\r\n      \"address\": {\r\n        \"address\": \"1197 First Street\",\r\n        \"city\": \"Fort Worth\",\r\n        \"state\": \"Rhode Island\",\r\n        \"stateCode\": \"RI\",\r\n        \"postalCode\": \"24771\",\r\n        \"coordinates\": {\r\n          \"lat\": -81.194833,\r\n          \"lng\": -87.948158\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"8d:2e:c2:d6:e7:a8\",\r\n      \"university\": \"University of Wisconsin--Madison\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"01/29\",\r\n        \"cardNumber\": \"6412128967460199\",\r\n        \"cardType\": \"Maestro\",\r\n        \"currency\": \"CNY\",\r\n        \"iban\": \"TS66YQ8R16OX7IJKLUONDQHP\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Marketing\",\r\n        \"name\": \"Nikolaus Inc\",\r\n        \"title\": \"Chief Executive Officer\",\r\n        \"address\": {\r\n          \"address\": \"930 Lincoln Street\",\r\n          \"city\": \"Austin\",\r\n          \"state\": \"Colorado\",\r\n          \"stateCode\": \"CO\",\r\n          \"postalCode\": \"47592\",\r\n          \"coordinates\": {\r\n            \"lat\": 87.970083,\r\n            \"lng\": -42.769351\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"297-762\",\r\n      \"ssn\": \"257-419-109\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 9,\r\n      \"Name\": \"Ethan\",\r\n      \"lastName\": \"Martinez\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 33,\r\n      \"gender\": \"male\",\r\n      \"email\": \"ethan.martinez@x.dummyjson.com\",\r\n      \"phone\": \"+92 933-608-5081\",\r\n      \"username\": \"ethanm\",\r\n      \"password\": \"ethanmpass\",\r\n      \"birthDate\": \"1991-2-12\",\r\n      \"image\": \"https://dummyjson.com/icon/ethanm/128\",\r\n      \"bloodGroup\": \"AB+\",\r\n      \"height\": 159.19,\r\n      \"weight\": 68.81,\r\n      \"eyeColor\": \"Hazel\",\r\n      \"hair\": {\r\n        \"color\": \"Purple\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"63.191.127.71\",\r\n      \"address\": {\r\n        \"address\": \"466 Pine Street\",\r\n        \"city\": \"San Antonio\",\r\n        \"state\": \"Louisiana\",\r\n        \"stateCode\": \"LA\",\r\n        \"postalCode\": \"72360\",\r\n        \"coordinates\": {\r\n          \"lat\": 74.074918,\r\n          \"lng\": -25.312703\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"59:e:9e:e3:29:da\",\r\n      \"university\": \"Syracuse University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"02/25\",\r\n        \"cardNumber\": \"7183482484317509\",\r\n        \"cardType\": \"Visa\",\r\n        \"currency\": \"CAD\",\r\n        \"iban\": \"CW5U5KS23U7JYD22TVQL7SIH\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Support\",\r\n        \"name\": \"Gorczany - Gottlieb\",\r\n        \"title\": \"Legal Counsel\",\r\n        \"address\": {\r\n          \"address\": \"1597 Oak Street\",\r\n          \"city\": \"Chicago\",\r\n          \"state\": \"Florida\",\r\n          \"stateCode\": \"FL\",\r\n          \"postalCode\": \"28100\",\r\n          \"coordinates\": {\r\n            \"lat\": -67.45208,\r\n            \"lng\": -23.209886\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"790-434\",\r\n      \"ssn\": \"569-650-348\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n " +
                "   {\r\n      \"id\": 10,\r\n      \"Name\": \"Isabella\",\r\n      \"lastName\": \"Anderson\",\r\n      \"maidenName\": \"Davis\",\r\n      \"age\": 31,\r\n      \"gender\": \"female\",\r\n      \"email\": \"isabella.anderson@x.dummyjson.com\",\r\n      \"phone\": \"+49 770-658-4885\",\r\n      \"username\": \"isabellad\",\r\n      \"password\": \"isabelladpass\",\r\n      \"birthDate\": \"1993-6-10\",\r\n      \"image\": \"https://dummyjson.com/icon/isabellad/128\",\r\n      \"bloodGroup\": \"A-\",\r\n      \"height\": 150.56,\r\n      \"weight\": 50.1,\r\n      \"eyeColor\": \"Brown\",\r\n      \"hair\": {\r\n        \"color\": \"Blonde\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"114.9.114.205\",\r\n      \"address\": {\r\n        \"address\": \"1964 Oak Street\",\r\n        \"city\": \"New York\",\r\n        \"state\": \"Utah\",\r\n        \"stateCode\": \"UT\",\r\n        \"postalCode\": \"89352\",\r\n        \"coordinates\": {\r\n          \"lat\": 41.331324,\r\n          \"lng\": 151.782727\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"b1:b0:d0:a2:82:80\",\r\n      \"university\": \"California Institute of Technology (Caltech)\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/27\",\r\n        \"cardNumber\": \"6118714010128731\",\r\n        \"cardType\": \"NPS\",\r\n        \"currency\": \"CNY\",\r\n        \"iban\": \"GBZRGDMKUOTO34HBCI7A986J\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Marketing\",\r\n        \"name\": \"Pollich - Hilpert\",\r\n        \"title\": \"Chief Financial Officer\",\r\n        \"address\": {\r\n          \"address\": \"1029 Adams Street\",\r\n          \"city\": \"San Diego\",\r\n          \"state\": \"Maryland\",\r\n          \"stateCode\": \"MD\",\r\n          \"postalCode\": \"63847\",\r\n          \"coordinates\": {\r\n            \"lat\": -25.843393,\r\n            \"lng\": -62.692681\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"127-297\",\r\n      \"ssn\": \"902-438-728\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 11,\r\n      \"Name\": \"Liam\",\r\n      \"lastName\": \"Garcia\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 29,\r\n      \"gender\": \"male\",\r\n      \"email\": \"liam.garcia@x.dummyjson.com\",\r\n      \"phone\": \"+92 870-217-6201\",\r\n      \"username\": \"liamg\",\r\n      \"password\": \"liamgpass\",\r\n      \"birthDate\": \"1995-6-6\",\r\n      \"image\": \"https://dummyjson.com/icon/liamg/128\",\r\n      \"bloodGroup\": \"AB-\",\r\n      \"height\": 162.32,\r\n      \"weight\": 93.16,\r\n      \"eyeColor\": \"Violet\",\r\n      \"hair\": {\r\n        \"color\": \"Red\",\r\n        \"type\": \"Wavy\"\r\n      },\r\n      \"ip\": \"56.201.85.9\",\r\n      \"address\": {\r\n        \"address\": \"576 Fifth Street\",\r\n        \"city\": \"Denver\",\r\n        \"state\": \"South Dakota\",\r\n        \"stateCode\": \"SD\",\r\n        \"postalCode\": \"57252\",\r\n        \"coordinates\": {\r\n          \"lat\": -66.218177,\r\n          \"lng\": -145.340165\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"31:9a:28:8b:99:6c\",\r\n      \"university\": \"Ohio State University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"02/27\",\r\n        \"cardNumber\": \"2302893002194899\",\r\n        \"cardType\": \"Discover\",\r\n        \"currency\": \"GBP\",\r\n        \"iban\": \"O8ENPRB9UVBL2EFZ7601KC09\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Services\",\r\n        \"name\": \"Considine - Torp\",\r\n        \"title\": \"Web Developer\",\r\n        \"address\": {\r\n          \"address\": \"27 Cedar Street\",\r\n          \"city\": \"Philadelphia\",\r\n          \"state\": \"Connecticut\",\r\n          \"stateCode\": \"CT\",\r\n          \"postalCode\": \"79574\",\r\n          \"coordinates\": {\r\n            \"lat\": -81.841588,\r\n            \"lng\": 31.79423\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"326-604\",\r\n      \"ssn\": \"933-784-949\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 12,\r\n      \"Name\": \"Mia\",\r\n      \"lastName\": \"Rodriguez\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 24,\r\n      \"gender\": \"female\",\r\n      \"email\": \"mia.rodriguez@x.dummyjson.com\",\r\n      \"phone\": \"+49 989-461-8403\",\r\n      \"username\": \"miar\",\r\n      \"password\": \"miarpass\",\r\n      \"birthDate\": \"2000-8-4\",\r\n      \"image\": \"https://dummyjson.com/icon/miar/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 188.08,\r\n      \"weight\": 56.03,\r\n      \"eyeColor\": \"Blue\",\r\n      \"hair\": {\r\n        \"color\": \"Purple\",\r\n        \"type\": \"Wavy\"\r\n      },\r\n      \"ip\": \"11.72.253.90\",\r\n      \"address\": {\r\n        \"address\": \"1627 Sixth Street\",\r\n        \"city\": \"Jacksonville\",\r\n        \"state\": \"West Virginia\",\r\n        \"stateCode\": \"WV\",\r\n        \"postalCode\": \"41810\",\r\n        \"coordinates\": {\r\n          \"lat\": 24.857497,\r\n          \"lng\": -34.865429\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"53:d7:a4:6:1e:58\",\r\n      \"university\": \"William & Mary\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/26\",\r\n        \"cardNumber\": \"1539872303456158\",\r\n        \"cardType\": \"Carte Bancaire\",\r\n        \"currency\": \"CAD\",\r\n        \"iban\": \"EBMD95RLK8B82ZAZNXBJ09V5\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Accounting\",\r\n        \"name\": \"Miller, Schowalter and Wisozk\",\r\n        \"title\": \"Business Analyst\",\r\n        \"address\": {\r\n          \"address\": \"1039 Washington Street\",\r\n          \"city\": \"Philadelphia\",\r\n          \"state\": \"New Jersey\",\r\n          \"stateCode\": \"NJ\",\r\n          \"postalCode\": \"57518\",\r\n          \"coordinates\": {\r\n            \"lat\": 85.455933,\r\n            \"lng\": 164.246103\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"754-660\",\r\n      \"ssn\": \"749-524-124\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n " +
                "   {\r\n      \"id\": 13,\r\n      \"Name\": \"Noah\",\r\n      \"lastName\": \"Hernandez\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 40,\r\n      \"gender\": \"male\",\r\n      \"email\": \"noah.hernandez@x.dummyjson.com\",\r\n      \"phone\": \"+49 393-605-6968\",\r\n      \"username\": \"noahh\",\r\n      \"password\": \"noahhpass\",\r\n      \"birthDate\": \"1984-6-5\",\r\n      \"image\": \"https://dummyjson.com/icon/noahh/128\",\r\n      \"bloodGroup\": \"AB+\",\r\n      \"height\": 188.62,\r\n      \"weight\": 69.49,\r\n      \"eyeColor\": \"Brown\",\r\n      \"hair\": {\r\n        \"color\": \"Red\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"169.154.126.57\",\r\n      \"address\": {\r\n        \"address\": \"1413 Maple Street\",\r\n        \"city\": \"New York\",\r\n        \"state\": \"North Dakota\",\r\n        \"stateCode\": \"ND\",\r\n        \"postalCode\": \"73696\",\r\n        \"coordinates\": {\r\n          \"lat\": -25.0377,\r\n          \"lng\": -151.70469\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"d4:fe:ae:8f:eb:a3\",\r\n      \"university\": \"New York University (NYU)\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/26\",\r\n        \"cardNumber\": \"1681772579326385\",\r\n        \"cardType\": \"Discover\",\r\n        \"currency\": \"SEK\",\r\n        \"iban\": \"G4UIZKIQVPJM9D31XQVR1E9Z\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Engineering\",\r\n        \"name\": \"Botsford, Marquardt and Roberts\",\r\n        \"title\": \"Database Administrator\",\r\n        \"address\": {\r\n          \"address\": \"62 Third Street\",\r\n          \"city\": \"Seattle\",\r\n          \"state\": \"Oregon\",\r\n          \"stateCode\": \"OR\",\r\n          \"postalCode\": \"83474\",\r\n          \"coordinates\": {\r\n            \"lat\": 19.490447,\r\n            \"lng\": -13.173207\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"877-628\",\r\n      \"ssn\": \"660-847-389\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 14,\r\n      \"Name\": \"Charlotte\",\r\n      \"lastName\": \"Lopez\",\r\n      \"maidenName\": \"Martinez\",\r\n      \"age\": 36,\r\n      \"gender\": \"female\",\r\n      \"email\": \"charlotte.lopez@x.dummyjson.com\",\r\n      \"phone\": \"+44 373-953-5028\",\r\n      \"username\": \"charlottem\",\r\n      \"password\": \"charlottempass\",\r\n      \"birthDate\": \"1988-6-8\",\r\n      \"image\": \"https://dummyjson.com/icon/charlottem/128\",\r\n      \"bloodGroup\": \"AB-\",\r\n      \"height\": 178.92,\r\n      \"weight\": 82.46,\r\n      \"eyeColor\": \"Brown\",\r\n      \"hair\": {\r\n        \"color\": \"Gray\",\r\n        \"type\": \"Kinky\"\r\n      },\r\n      \"ip\": \"119.103.95.60\",\r\n      \"address\": {\r\n        \"address\": \"208 Second Street\",\r\n        \"city\": \"Columbus\",\r\n        \"state\": \"Ohio\",\r\n        \"stateCode\": \"OH\",\r\n        \"postalCode\": \"42044\",\r\n        \"coordinates\": {\r\n          \"lat\": -44.443762,\r\n          \"lng\": -151.420561\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"f6:ff:37:aa:6c:f1\",\r\n      \"university\": \"Northeastern University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"02/27\",\r\n        \"cardNumber\": \"5675368650551956\",\r\n        \"cardType\": \"Maestro\",\r\n        \"currency\": \"CNY\",\r\n        \"iban\": \"FKK6U634LGI3E7N517DLVVTL\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Accounting\",\r\n        \"name\": \"Zulauf and Sons\",\r\n        \"title\": \"Chief Executive Officer\",\r\n        \"address\": {\r\n          \"address\": \"569 Jefferson Street\",\r\n          \"city\": \"Los Angeles\",\r\n          \"state\": \"Montana\",\r\n          \"stateCode\": \"MT\",\r\n          \"postalCode\": \"17779\",\r\n          \"coordinates\": {\r\n            \"lat\": -18.371256,\r\n            \"lng\": 22.566258\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"364-782\",\r\n      \"ssn\": \"255-491-479\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 15,\r\n      \"Name\": \"William\",\r\n      \"lastName\": \"Gonzalez\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 32,\r\n      \"gender\": \"male\",\r\n      \"email\": \"william.gonzalez@x.dummyjson.com\",\r\n      \"phone\": \"+81 905-252-7319\",\r\n      \"username\": \"williamg\",\r\n      \"password\": \"williamgpass\",\r\n      \"birthDate\": \"1992-3-27\",\r\n      \"image\": \"https://dummyjson.com/icon/williamg/128\",\r\n      \"bloodGroup\": \"B-\",\r\n      \"height\": 173.21,\r\n      \"weight\": 82.41,\r\n      \"eyeColor\": \"Hazel\",\r\n      \"hair\": {\r\n        \"color\": \"Gray\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"250.2.241.204\",\r\n      \"address\": {\r\n        \"address\": \"31 Maple Street\",\r\n        \"city\": \"San Jose\",\r\n        \"state\": \"Utah\",\r\n        \"stateCode\": \"UT\",\r\n        \"postalCode\": \"78243\",\r\n        \"coordinates\": {\r\n          \"lat\": 8.152876,\r\n          \"lng\": 113.29799\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"f5:68:28:f9:ec:89\",\r\n      \"university\": \"Tufts University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"03/27\",\r\n        \"cardNumber\": \"6053000793215148\",\r\n        \"cardType\": \"Mir\",\r\n        \"currency\": \"EUR\",\r\n        \"iban\": \"AR01SNDMKGECX0EYH7UCW61W\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Marketing\",\r\n        \"name\": \"Spinka - Dickinson\",\r\n        \"title\": \"Software Architect\",\r\n        \"address\": {\r\n          \"address\": \"1538 Eighth Street\",\r\n          \"city\": \"San Jose\",\r\n          \"state\": \"Missouri\",\r\n          \"stateCode\": \"MO\",\r\n          \"postalCode\": \"29673\",\r\n          \"coordinates\": {\r\n            \"lat\": 24.169361,\r\n            \"lng\": -29.395167\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"830-515\",\r\n      \"ssn\": \"690-544-755\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"moderator\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 16,\r\n      \"Name\": \"Avery\",\r\n      \"lastName\": \"Perez\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 25,\r\n      \"gender\": \"female\",\r\n      \"email\": \"avery.perez@x.dummyjson.com\",\r\n      \"phone\": \"+61 731-431-3457\",\r\n      \"username\": \"averyp\",\r\n      \"password\": \"averyppass\",\r\n      \"birthDate\": \"1999-3-10\",\r\n      \"image\": \"https://dummyjson.com/icon/averyp/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 172.68,\r\n      \"weight\": 93.9,\r\n      \"eyeColor\": \"Brown\",\r\n      \"hair\": {\r\n        \"color\": \"Green\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"131.217.4.214\",\r\n      \"address\": {\r\n        \"address\": \"1125 First Street\",\r\n        \"city\": \"Columbus\",\r\n        \"state\": \"Iowa\",\r\n        \"stateCode\": \"IA\",\r\n        \"postalCode\": \"30973\",\r\n        \"coordinates\": {\r\n          \"lat\": 12.789127,\r\n          \"lng\": 85.792598\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"b3:ff:f3:c5:37:46\",\r\n      \"university\": \"Harvard University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"04/27\",\r\n        \"cardNumber\": \"0961014686718571\",\r\n        \"cardType\": \"Carte Bancaire\",\r\n        \"currency\": \"USD\",\r\n        \"iban\": \"28JYZAY4KYT48YI8QW40PWXR\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Accounting\",\r\n        \"name\": \"Herzog Inc\",\r\n        \"title\": \"Database Administrator\",\r\n        \"address\": {\r\n          \"address\": \"183 Maple Street\",\r\n          \"city\": \"New York\",\r\n          \"state\": \"Rhode Island\",\r\n          \"stateCode\": \"RI\",\r\n          \"postalCode\": \"45238\",\r\n          \"coordinates\": {\r\n            \"lat\": -53.318189,\r\n            \"lng\": 105.835271\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"348-493\",\r\n      \"ssn\": \"679-523-686\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 17,\r\n      \"Name\": \"Evelyn\",\r\n      \"lastName\": \"Sanchez\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 37,\r\n      \"gender\": \"female\",\r\n      \"email\": \"evelyn.sanchez@x.dummyjson.com\",\r\n      \"phone\": \"+1 623-880-6871\",\r\n      \"username\": \"evelyns\",\r\n      \"password\": \"evelynspass\",\r\n      \"birthDate\": \"1987-10-13\",\r\n      \"image\": \"https://dummyjson.com/icon/evelyns/128\",\r\n      \"bloodGroup\": \"B+\",\r\n      \"height\": 184.08,\r\n      \"weight\": 83.15,\r\n      \"eyeColor\": \"Violet\",\r\n      \"hair\": {\r\n        \"color\": \"Blue\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"87.114.135.146\",\r\n      \"address\": {\r\n        \"address\": \"1170 Lincoln Street\",\r\n        \"city\": \"San Diego\",\r\n        \"state\": \"Wyoming\",\r\n        \"stateCode\": \"WY\",\r\n        \"postalCode\": \"43423\",\r\n        \"coordinates\": {\r\n          \"lat\": -83.31484,\r\n          \"lng\": 11.768071\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"f8:e5:bd:43:bc:d8\",\r\n      \"university\": \"Washington University in St. Louis\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"04/29\",\r\n        \"cardNumber\": \"4557521697420096\",\r\n        \"cardType\": \"UnionPay\",\r\n        \"currency\": \"SEK\",\r\n        \"iban\": \"KN8XAPR2J5UB8AKDI1EVJ56R\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Support\",\r\n        \"name\": \"Predovic - Johns\",\r\n        \"title\": \"Chief Financial Officer\",\r\n        \"address\": {\r\n          \"address\": \"1802 Ninth Street\",\r\n          \"city\": \"San Diego\",\r\n          \"state\": \"Minnesota\",\r\n          \"stateCode\": \"MN\",\r\n          \"postalCode\": \"89416\",\r\n          \"coordinates\": {\r\n            \"lat\": 29.034592,\r\n            \"lng\": -78.004598\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"604-817\",\r\n      \"ssn\": \"689-332-644\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 18,\r\n      \"Name\": \"Logan\",\r\n      \"lastName\": \"Torres\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 31,\r\n      \"gender\": \"male\",\r\n      \"email\": \"logan.torres@x.dummyjson.com\",\r\n      \"phone\": \"+81 507-434-8733\",\r\n      \"username\": \"logant\",\r\n      \"password\": \"logantpass\",\r\n      \"birthDate\": \"1993-10-26\",\r\n      \"image\": \"https://dummyjson.com/icon/logant/128\",\r\n      \"bloodGroup\": \"A+\",\r\n      \"height\": 190.04,\r\n      \"weight\": 72.43,\r\n      \"eyeColor\": \"Green\",\r\n      \"hair\": {\r\n        \"color\": \"Green\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"155.98.15.162\",\r\n      \"address\": {\r\n        \"address\": \"907 Seventh Street\",\r\n        \"city\": \"Columbus\",\r\n        \"state\": \"Arkansas\",\r\n        \"stateCode\": \"AR\",\r\n        \"postalCode\": \"78805\",\r\n        \"coordinates\": {\r\n          \"lat\": -64.846516,\r\n          \"lng\": 174.775744\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"40:d:5c:1:7d:bf\",\r\n      \"university\": \"University of Illinois--Urbana-Champaign\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/26\",\r\n        \"cardNumber\": \"7884268130452098\",\r\n        \"cardType\": \"UnionPay\",\r\n        \"currency\": \"NZD\",\r\n        \"iban\": \"HZM7V9PYHPZBN72IDFPXGN8Q\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Training\",\r\n        \"name\": \"Jast - Nader\",\r\n        \"title\": \"Data Analyst\",\r\n        \"address\": {\r\n          \"address\": \"947 Main Street\",\r\n          \"city\": \"Denver\",\r\n          \"state\": \"Minnesota\",\r\n          \"stateCode\": \"MN\",\r\n          \"postalCode\": \"71896\",\r\n          \"coordinates\": {\r\n            \"lat\": -24.654063,\r\n            \"lng\": -147.255268\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"576-218\",\r\n      \"ssn\": \"806-639-934\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 19,\r\n      \"Name\": \"Abigail\",\r\n      \"lastName\": \"Rivera\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 28,\r\n      \"gender\": \"female\",\r\n      \"email\": \"abigail.rivera@x.dummyjson.com\",\r\n      \"phone\": \"+91 228-363-7806\",\r\n      \"username\": \"abigailr\",\r\n      \"password\": \"abigailrpass\",\r\n      \"birthDate\": \"1996-10-11\",\r\n      \"image\": \"https://dummyjson.com/icon/abigailr/128\",\r\n      \"bloodGroup\": \"B+\",\r\n      \"height\": 186.39,\r\n      \"weight\": 74.61,\r\n      \"eyeColor\": \"Violet\",\r\n      \"hair\": {\r\n        \"color\": \"Blue\",\r\n        \"type\": \"Kinky\"\r\n      },\r\n      \"ip\": \"19.183.240.94\",\r\n      \"address\": {\r\n        \"address\": \"996 Oak Street\",\r\n        \"city\": \"Chicago\",\r\n        \"state\": \"New Mexico\",\r\n        \"stateCode\": \"NM\",\r\n        \"postalCode\": \"11407\",\r\n        \"coordinates\": {\r\n          \"lat\": 44.321308,\r\n          \"lng\": -3.723903\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"1d:a6:58:2a:e5:e4\",\r\n      \"university\": \"California Institute of Technology (Caltech)\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"02/28\",\r\n        \"cardNumber\": \"4832361886407551\",\r\n        \"cardType\": \"RuPay\",\r\n        \"currency\": \"BRL\",\r\n        \"iban\": \"O02LHDNNFCVSM6D4H81DIQHE\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Human Resources\",\r\n        \"name\": \"Prohaska - Thiel\",\r\n        \"title\": \"Business Analyst\",\r\n        \"address\": {\r\n          \"address\": \"1402 Adams Street\",\r\n          \"city\": \"Austin\",\r\n          \"state\": \"Wisconsin\",\r\n          \"stateCode\": \"WI\",\r\n          \"postalCode\": \"51456\",\r\n          \"coordinates\": {\r\n            \"lat\": 25.672938,\r\n            \"lng\": -76.54967\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"173-637\",\r\n      \"ssn\": \"655-823-929\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n " +
                "   {\r\n      \"id\": 20,\r\n      \"Name\": \"Jackson\",\r\n      \"lastName\": \"Evans\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 34,\r\n      \"gender\": \"male\",\r\n      \"email\": \"jackson.evans@x.dummyjson.com\",\r\n      \"phone\": \"+44 468-628-6686\",\r\n      \"username\": \"jacksone\",\r\n      \"password\": \"jacksonepass\",\r\n      \"birthDate\": \"1990-11-30\",\r\n      \"image\": \"https://dummyjson.com/icon/jacksone/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 162.57,\r\n      \"weight\": 74.37,\r\n      \"eyeColor\": \"Green\",\r\n      \"hair\": {\r\n        \"color\": \"Red\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"221.127.144.198\",\r\n      \"address\": {\r\n        \"address\": \"1873 Main Street\",\r\n        \"city\": \"New York\",\r\n        \"state\": \"Arkansas\",\r\n        \"stateCode\": \"AR\",\r\n        \"postalCode\": \"26600\",\r\n        \"coordinates\": {\r\n          \"lat\": 34.722451,\r\n          \"lng\": 63.448927\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"81:14:1:97:88:85\",\r\n      \"university\": \"Ohio State University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"04/26\",\r\n        \"cardNumber\": \"2109192842527801\",\r\n        \"cardType\": \"BC Card\",\r\n        \"currency\": \"EUR\",\r\n        \"iban\": \"TX26FO9B7YR2VHYDSJBE32AX\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Legal\",\r\n        \"name\": \"Kuhlman LLC\",\r\n        \"title\": \"Web Developer\",\r\n        \"address\": {\r\n          \"address\": \"1706 First Street\",\r\n          \"city\": \"Chicago\",\r\n          \"state\": \"Hawaii\",\r\n          \"stateCode\": \"HI\",\r\n          \"postalCode\": \"34725\",\r\n          \"coordinates\": {\r\n            \"lat\": -80.416937,\r\n            \"lng\": -83.224516\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"843-260\",\r\n      \"ssn\": \"248-787-886\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 21,\r\n      \"Name\": \"Madison\",\r\n      \"lastName\": \"Collins\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 26,\r\n      \"gender\": \"female\",\r\n      \"email\": \"madison.collins@x.dummyjson.com\",\r\n      \"phone\": \"+81 259-957-5711\",\r\n      \"username\": \"madisonc\",\r\n      \"password\": \"madisoncpass\",\r\n      \"birthDate\": \"1998-3-7\",\r\n      \"image\": \"https://dummyjson.com/icon/madisonc/128\",\r\n      \"bloodGroup\": \"B-\",\r\n      \"height\": 189.28,\r\n      \"weight\": 56.96,\r\n      \"eyeColor\": \"Red\",\r\n      \"hair\": {\r\n        \"color\": \"Gray\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"85.34.1.204\",\r\n      \"address\": {\r\n        \"address\": \"1892 Lincoln Street\",\r\n        \"city\": \"Philadelphia\",\r\n        \"state\": \"New Jersey\",\r\n        \"stateCode\": \"NJ\",\r\n        \"postalCode\": \"62091\",\r\n        \"coordinates\": {\r\n          \"lat\": 52.993694,\r\n          \"lng\": 160.486892\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"13:b0:d0:23:4d:26\",\r\n      \"university\": \"University of Pennsylvania\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"04/28\",\r\n        \"cardNumber\": \"5549175461210252\",\r\n        \"cardType\": \"Mir\",\r\n        \"currency\": \"CNY\",\r\n        \"iban\": \"Y0WSN5IED255808SIYBUOMWO\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Engineering\",\r\n        \"name\": \"Mayer - Smitham\",\r\n        \"title\": \"Chief Technology Officer\",\r\n        \"address\": {\r\n          \"address\": \"1438 Main Street\",\r\n          \"city\": \"San Diego\",\r\n          \"state\": \"Delaware\",\r\n          \"stateCode\": \"DE\",\r\n          \"postalCode\": \"63144\",\r\n          \"coordinates\": {\r\n            \"lat\": 1.629613,\r\n            \"lng\": 23.232982\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"716-166\",\r\n      \"ssn\": \"457-258-950\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 22,\r\n      \"Name\": \"Elijah\",\r\n      \"lastName\": \"Stewart\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 33,\r\n      \"gender\": \"male\",\r\n      \"email\": \"elijah.stewart@x.dummyjson.com\",\r\n      \"phone\": \"+44 468-357-7872\",\r\n      \"username\": \"elijahs\",\r\n      \"password\": \"elijahspass\",\r\n      \"birthDate\": \"1991-10-22\",\r\n      \"image\": \"https://dummyjson.com/icon/elijahs/128\",\r\n      \"bloodGroup\": \"A-\",\r\n      \"height\": 195.33,\r\n      \"weight\": 81.64,\r\n      \"eyeColor\": \"Blue\",\r\n      \"hair\": {\r\n        \"color\": \"Purple\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"23.87.135.62\",\r\n      \"address\": {\r\n        \"address\": \"1701 Eighth Street\",\r\n        \"city\": \"Columbus\",\r\n        \"state\": \"Illinois\",\r\n        \"stateCode\": \"IL\",\r\n        \"postalCode\": \"31585\",\r\n        \"coordinates\": {\r\n          \"lat\": -54.833799,\r\n          \"lng\": -174.504027\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"75:17:c6:35:fc:6d\",\r\n      \"university\": \"Georgetown University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/27\",\r\n        \"cardNumber\": \"0798116671286564\",\r\n        \"cardType\": \"JCB\",\r\n        \"currency\": \"GBP\",\r\n        \"iban\": \"E1XUHCC1N39WGU6XESSK1CAO\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Legal\",\r\n        \"name\": \"Langworth Group\",\r\n        \"title\": \"Business Analyst\",\r\n        \"address\": {\r\n          \"address\": \"155 Ninth Street\",\r\n          \"city\": \"Washington\",\r\n          \"state\": \"South Dakota\",\r\n          \"stateCode\": \"SD\",\r\n          \"postalCode\": \"19039\",\r\n          \"coordinates\": {\r\n            \"lat\": 61.279254,\r\n            \"lng\": -12.607767\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"520-394\",\r\n      \"ssn\": \"287-380-801\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 23,\r\n      \"Name\": \"Chloe\",\r\n      \"lastName\": \"Morales\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 39,\r\n      \"gender\": \"female\",\r\n      \"email\": \"chloe.morales@x.dummyjson.com\",\r\n      \"phone\": \"+92 468-541-7133\",\r\n      \"username\": \"chloem\",\r\n      \"password\": \"chloempass\",\r\n      \"birthDate\": \"1985-4-21\",\r\n      \"image\": \"https://dummyjson.com/icon/chloem/128\",\r\n      \"bloodGroup\": \"O+\",\r\n      \"height\": 185.07,\r\n      \"weight\": 63.97,\r\n      \"eyeColor\": \"Brown\",\r\n      \"hair\": {\r\n        \"color\": \"Red\",\r\n        \"type\": \"Kinky\"\r\n      },\r\n      \"ip\": \"66.78.20.21\",\r\n      \"address\": {\r\n        \"address\": \"401 Fourth Street\",\r\n        \"city\": \"Dallas\",\r\n        \"state\": \"New Jersey\",\r\n        \"stateCode\": \"NJ\",\r\n        \"postalCode\": \"54972\",\r\n        \"coordinates\": {\r\n          \"lat\": -30.190759,\r\n          \"lng\": -58.705979\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"fc:f:29:e1:37:b8\",\r\n      \"university\": \"Syracuse University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/28\",\r\n        \"cardNumber\": \"3150496938377346\",\r\n        \"cardType\": \"American Express\",\r\n        \"currency\": \"PKR\",\r\n        \"iban\": \"P7YLGOOBWBD1SRWDWSFO3PZ0\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Sales\",\r\n        \"name\": \"Grady LLC\",\r\n        \"title\": \"Database Administrator\",\r\n        \"address\": {\r\n          \"address\": \"269 Third Street\",\r\n          \"city\": \"Houston\",\r\n          \"state\": \"North Carolina\",\r\n          \"stateCode\": \"NC\",\r\n          \"postalCode\": \"10385\",\r\n          \"coordinates\": {\r\n            \"lat\": 40.098115,\r\n            \"lng\": -1.762972\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"913-597\",\r\n      \"ssn\": \"938-883-163\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 24,\r\n      \"Name\": \"Mateo\",\r\n      \"lastName\": \"Nguyen\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 30,\r\n      \"gender\": \"male\",\r\n      \"email\": \"mateo.nguyen@x.dummyjson.com\",\r\n      \"phone\": \"+1 341-597-6694\",\r\n      \"username\": \"mateon\",\r\n      \"password\": \"mateonpass\",\r\n      \"birthDate\": \"1994-6-2\",\r\n      \"image\": \"https://dummyjson.com/icon/mateon/128\",\r\n      \"bloodGroup\": \"O+\",\r\n      \"height\": 174.29,\r\n      \"weight\": 59.98,\r\n      \"eyeColor\": \"Red\",\r\n      \"hair\": {\r\n        \"color\": \"Purple\",\r\n        \"type\": \"Wavy\"\r\n      },\r\n      \"ip\": \"192.57.144.7\",\r\n      \"address\": {\r\n        \"address\": \"1578 Fourth Street\",\r\n        \"city\": \"Columbus\",\r\n        \"state\": \"Missouri\",\r\n        \"stateCode\": \"MO\",\r\n        \"postalCode\": \"20673\",\r\n        \"coordinates\": {\r\n          \"lat\": -32.828675,\r\n          \"lng\": -82.557354\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"a7:26:10:7a:36:29\",\r\n      \"university\": \"Columbia University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"03/26\",\r\n        \"cardNumber\": \"5545852224851851\",\r\n        \"cardType\": \"JCB\",\r\n        \"currency\": \"TRY\",\r\n        \"iban\": \"WEBE9SBX588VFUCVCA6KFHWB\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Accounting\",\r\n        \"name\": \"Spinka LLC\",\r\n        \"title\": \"Business Analyst\",\r\n        \"address\": {\r\n          \"address\": \"1967 Jefferson Street\",\r\n          \"city\": \"Dallas\",\r\n          \"state\": \"Louisiana\",\r\n          \"stateCode\": \"LA\",\r\n          \"postalCode\": \"78527\",\r\n          \"coordinates\": {\r\n            \"lat\": 75.982676,\r\n            \"lng\": 164.459743\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"229-249\",\r\n      \"ssn\": \"416-877-230\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 25,\r\n      \"Name\": \"Harper\",\r\n      \"lastName\": \"Kelly\",\r\n      \"maidenName\": \"Evans\",\r\n      \"age\": 27,\r\n      \"gender\": \"female\",\r\n      \"email\": \"harper.kelly@x.dummyjson.com\",\r\n      \"phone\": \"+92 518-863-2863\",\r\n      \"username\": \"harpere\",\r\n      \"password\": \"harperepass\",\r\n      \"birthDate\": \"1997-3-3\",\r\n      \"image\": \"https://dummyjson.com/icon/harpere/128\",\r\n      \"bloodGroup\": \"AB-\",\r\n      \"height\": 184.32,\r\n      \"weight\": 81.69,\r\n      \"eyeColor\": \"Amber\",\r\n      \"hair\": {\r\n        \"color\": \"Red\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"174.111.61.162\",\r\n      \"address\": {\r\n        \"address\": \"1591 Adams Street\",\r\n        \"city\": \"Philadelphia\",\r\n        \"state\": \"New York\",\r\n        \"stateCode\": \"NY\",\r\n        \"postalCode\": \"69521\",\r\n        \"coordinates\": {\r\n          \"lat\": -26.832913,\r\n          \"lng\": -75.445017\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"b:ff:33:67:94:e4\",\r\n      \"university\": \"Boston College\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"04/26\",\r\n        \"cardNumber\": \"1298153007505587\",\r\n        \"cardType\": \"RuPay\",\r\n        \"currency\": \"JPY\",\r\n        \"iban\": \"DJI19LCUNUHP6YSGPY52D5VG\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Legal\",\r\n        \"name\": \"Leffler, Rolfson and Becker\",\r\n        \"title\": \"Business Development Manager\",\r\n        \"address\": {\r\n          \"address\": \"16 Maple Street\",\r\n          \"city\": \"Austin\",\r\n          \"state\": \"North Carolina\",\r\n          \"stateCode\": \"NC\",\r\n          \"postalCode\": \"68274\",\r\n          \"coordinates\": {\r\n            \"lat\": -15.423746,\r\n            \"lng\": 149.298887\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"592-557\",\r\n      \"ssn\": \"209-544-548\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 26,\r\n      \"Name\": \"Evelyn\",\r\n      \"lastName\": \"Gonzalez\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 35,\r\n      \"gender\": \"female\",\r\n      \"email\": \"evelyn.gonzalez@x.dummyjson.com\",\r\n      \"phone\": \"+61 708-508-4638\",\r\n      \"username\": \"evelyng\",\r\n      \"password\": \"evelyngpass\",\r\n      \"birthDate\": \"1989-2-5\",\r\n      \"image\": \"https://dummyjson.com/icon/evelyng/128\",\r\n      \"bloodGroup\": \"O+\",\r\n      \"height\": 168.94,\r\n      \"weight\": 58.47,\r\n      \"eyeColor\": \"Red\",\r\n      \"hair\": {\r\n        \"color\": \"Black\",\r\n        \"type\": \"Wavy\"\r\n      },\r\n      \"ip\": \"42.52.74.232\",\r\n      \"address\": {\r\n        \"address\": \"1065 Lincoln Street\",\r\n        \"city\": \"Dallas\",\r\n        \"state\": \"Maine\",\r\n        \"stateCode\": \"ME\",\r\n        \"postalCode\": \"84898\",\r\n        \"coordinates\": {\r\n          \"lat\": 67.768359,\r\n          \"lng\": 71.268643\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"89:5e:5a:2a:72:42\",\r\n      \"university\": \"Washington University in St. Louis\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"03/28\",\r\n        \"cardNumber\": \"9584313788145560\",\r\n        \"cardType\": \"RuPay\",\r\n        \"currency\": \"INR\",\r\n        \"iban\": \"X4UPULQG61VIGA97USY7AAEB\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Accounting\",\r\n        \"name\": \"Tromp, Gaylord and Weber\",\r\n        \"title\": \"Project Manager\",\r\n        \"address\": {\r\n          \"address\": \"584 Ninth Street\",\r\n          \"city\": \"Jacksonville\",\r\n          \"state\": \"Wisconsin\",\r\n          \"stateCode\": \"WI\",\r\n          \"postalCode\": \"45633\",\r\n          \"coordinates\": {\r\n            \"lat\": 26.014021,\r\n            \"lng\": 40.572436\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"569-275\",\r\n      \"ssn\": \"487-680-127\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 27,\r\n      \"Name\": \"Daniel\",\r\n      \"lastName\": \"Cook\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 41,\r\n      \"gender\": \"male\",\r\n      \"email\": \"daniel.cook@x.dummyjson.com\",\r\n      \"phone\": \"+44 254-761-6843\",\r\n      \"username\": \"danielc\",\r\n      \"password\": \"danielcpass\",\r\n      \"birthDate\": \"1983-12-25\",\r\n      \"image\": \"https://dummyjson.com/icon/danielc/128\",\r\n      \"bloodGroup\": \"AB+\",\r\n      \"height\": 186.21,\r\n      \"weight\": 83.72,\r\n      \"eyeColor\": \"Brown\",\r\n      \"hair\": {\r\n        \"color\": \"Blonde\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"1.61.73.142\",\r\n      \"address\": {\r\n        \"address\": \"1163 Pine Street\",\r\n        \"city\": \"Los Angeles\",\r\n        \"state\": \"Nevada\",\r\n        \"stateCode\": \"NV\",\r\n        \"postalCode\": \"58781\",\r\n        \"coordinates\": {\r\n          \"lat\": -3.456681,\r\n          \"lng\": -134.937482\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"6e:73:dc:3a:85:10\",\r\n      \"university\": \"Columbia University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"01/26\",\r\n        \"cardNumber\": \"8452555751345228\",\r\n        \"cardType\": \"Korean Express\",\r\n        \"currency\": \"NZD\",\r\n        \"iban\": \"A8DBPECO4X6D09WYOVT8UZK8\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Support\",\r\n        \"name\": \"Morissette, Baumbach and Auer\",\r\n        \"title\": \"Legal Counsel\",\r\n        \"address\": {\r\n          \"address\": \"938 Fifth Street\",\r\n          \"city\": \"San Francisco\",\r\n          \"state\": \"South Dakota\",\r\n          \"stateCode\": \"SD\",\r\n          \"postalCode\": \"45305\",\r\n          \"coordinates\": {\r\n            \"lat\": 21.323588,\r\n            \"lng\": -83.531427\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"585-905\",\r\n      \"ssn\": \"645-515-583\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 28,\r\n      \"Name\": \"Lily\",\r\n      \"lastName\": \"Lee\",\r\n      \"maidenName\": \"Brown\",\r\n      \"age\": 29,\r\n      \"gender\": \"female\",\r\n      \"email\": \"lily.lee@x.dummyjson.com\",\r\n      \"phone\": \"+1 808-757-9867\",\r\n      \"username\": \"lilyb\",\r\n      \"password\": \"lilybpass\",\r\n      \"birthDate\": \"1995-12-3\",\r\n      \"image\": \"https://dummyjson.com/icon/lilyb/128\",\r\n      \"bloodGroup\": \"AB-\",\r\n      \"height\": 181.42,\r\n      \"weight\": 51.49,\r\n      \"eyeColor\": \"Gray\",\r\n      \"hair\": {\r\n        \"color\": \"Purple\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"67.184.255.96\",\r\n      \"address\": {\r\n        \"address\": \"1946 Oak Street\",\r\n        \"city\": \"Phoenix\",\r\n        \"state\": \"Massachusetts\",\r\n        \"stateCode\": \"MA\",\r\n        \"postalCode\": \"41540\",\r\n        \"coordinates\": {\r\n          \"lat\": -9.87059,\r\n          \"lng\": -72.336845\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"18:b6:c7:a:50:3f\",\r\n      \"university\": \"Johns Hopkins University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/29\",\r\n        \"cardNumber\": \"2903637820228856\",\r\n        \"cardType\": \"Visa\",\r\n        \"currency\": \"JPY\",\r\n        \"iban\": \"BKX6ZWB8UJZD09RFOWFPPD3C\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Product Management\",\r\n        \"name\": \"Cremin Inc\",\r\n        \"title\": \"Quality Assurance Engineer\",\r\n        \"address\": {\r\n          \"address\": \"1735 Cedar Street\",\r\n          \"city\": \"Phoenix\",\r\n          \"state\": \"Wyoming\",\r\n          \"stateCode\": \"WY\",\r\n          \"postalCode\": \"85797\",\r\n          \"coordinates\": {\r\n            \"lat\": 72.231441,\r\n            \"lng\": -158.147245\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"229-776\",\r\n      \"ssn\": \"358-185-671\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n   " +
                " {\r\n      \"id\": 29,\r\n      \"Name\": \"Henry\",\r\n      \"lastName\": \"Hill\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 38,\r\n      \"gender\": \"male\",\r\n      \"email\": \"henry.hill@x.dummyjson.com\",\r\n      \"phone\": \"+1 240-833-4680\",\r\n      \"username\": \"henryh\",\r\n      \"password\": \"henryhpass\",\r\n      \"birthDate\": \"1986-8-19\",\r\n      \"image\": \"https://dummyjson.com/icon/henryh/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 180.25,\r\n      \"weight\": 95.84,\r\n      \"eyeColor\": \"Gray\",\r\n      \"hair\": {\r\n        \"color\": \"Black\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"194.43.55.202\",\r\n      \"address\": {\r\n        \"address\": \"1837 Maple Street\",\r\n        \"city\": \"Indianapolis\",\r\n        \"state\": \"Delaware\",\r\n        \"stateCode\": \"DE\",\r\n        \"postalCode\": \"81783\",\r\n        \"coordinates\": {\r\n          \"lat\": 35.498256,\r\n          \"lng\": 154.088476\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"fa:c3:1b:21:5f:44\",\r\n      \"university\": \"University of Illinois--Urbana-Champaign\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"02/26\",\r\n        \"cardNumber\": \"7262597174206766\",\r\n        \"cardType\": \"Diners Club International\",\r\n        \"currency\": \"SEK\",\r\n        \"iban\": \"7N3JP8KN9AUNXOWRQGAU2JX6\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Services\",\r\n        \"name\": \"Gerlach, Funk and Schoen\",\r\n        \"title\": \"Sales Manager\",\r\n        \"address\": {\r\n          \"address\": \"1651 Lincoln Street\",\r\n          \"city\": \"San Francisco\",\r\n          \"state\": \"West Virginia\",\r\n          \"stateCode\": \"WV\",\r\n          \"postalCode\": \"61805\",\r\n          \"coordinates\": {\r\n            \"lat\": -59.936335,\r\n            \"lng\": -12.405368\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"118-957\",\r\n      \"ssn\": \"925-686-100\",\r\n      \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    },\r\n  " +
                "  {\r\n      \"id\": 30,\r\n      \"Name\": \"Addison\",\r\n      \"lastName\": \"Wright\",\r\n      \"maidenName\": \"\",\r\n      \"age\": 32,\r\n      \"gender\": \"female\",\r\n      \"email\": \"addison.wright@x.dummyjson.com\",\r\n      \"phone\": \"+1 514-384-3300\",\r\n      \"username\": \"addisonw\",\r\n      \"password\": \"addisonwpass\",\r\n      \"birthDate\": \"1992-1-3\",\r\n      \"image\": \"https://dummyjson.com/icon/addisonw/128\",\r\n      \"bloodGroup\": \"B+\",\r\n      \"height\": 179.32,\r\n      \"weight\": 76.93,\r\n      \"eyeColor\": \"Brown\",\r\n      \"hair\": {\r\n        \"color\": \"Blonde\",\r\n        \"type\": \"Straight\"\r\n      },\r\n      \"ip\": \"11.35.69.81\",\r\n      \"address\": {\r\n        \"address\": \"568 Tenth Street\",\r\n        \"city\": \"San Francisco\",\r\n        \"state\": \"Montana\",\r\n        \"stateCode\": \"MT\",\r\n        \"postalCode\": \"54698\",\r\n        \"coordinates\": {\r\n          \"lat\": 20.946052,\r\n          \"lng\": 100.228822\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"fb:0:94:21:16:c\",\r\n      \"university\": \"Syracuse University\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"05/28\",\r\n        \"cardNumber\": \"3756638438861539\",\r\n        \"cardType\": \"Carte Bancaire\",\r\n        \"currency\": \"JPY\",\r\n        \"iban\": \"OOPQTNZ74OLPKVT7TGB89UQL\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Services\",\r\n        \"name\": \"Kreiger Inc\",\r\n        \"title\": \"Human Resources Manager\",\r\n        \"address\": {\r\n          \"address\": \"1173 Eighth Street\",\r\n          \"city\": \"San Diego\",\r\n          \"state\": \"Michigan\",\r\n          \"stateCode\": \"MI\",\r\n          \"postalCode\": \"85777\",\r\n          \"coordinates\": {\r\n            \"lat\": 65.324413,\r\n            \"lng\": 87.142893\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"415-286\",\r\n      \"ssn\": \"804-492-390\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"user\"\r\n    }\r\n  ]";

            EmployeesDTO tempJson = new EmployeesDTO();
            EmployeesDTO nextEJson = new EmployeesDTO();

            var jsonFiles = Directory.EnumerateFiles(".").Where(p => p.EndsWith(".json"));


            List<EmployeesDTO> listTemporaryDto = new List<EmployeesDTO>();


            var path4 = Path.Combine(Environment.CurrentDirectory, "json.txt");
            var json4 = File.ReadAllText(path4);
            var currency = Newtonsoft.Json.JsonConvert.DeserializeObject<EmployeesDTO>(json4);

            var employeesList2 = Newtonsoft.Json.JsonConvert.DeserializeObject<List<EmployeesDTO>>(fileJson1);

            var pathDataJson = Path.Combine(Environment.CurrentDirectory, "dataJson.json");
            var jsonDataJson = File.ReadAllText(pathDataJson);
            var currencyDataJson = Newtonsoft.Json.JsonConvert.DeserializeObject<List<EmployeesDTO>>(jsonDataJson);

            string command = "";
            string[,] arrEmps = new string[100, 2];
            while (!command.ToLower().Contains("q"))
            {
                Console.Write(">> ");
                command = Console.ReadLine();
                switch (command)
                {
                    case "list":
                        int index = 0;
                        foreach (var employee in employeesList)
                        {
                            Console.WriteLine($"{index} Name: {employee.Name} | Phone: {employee.Phone}");
                            ++index;
                        }
                        Console.WriteLine("Печать данных файла:");
                        for (int i = 0; i < arrEmps.GetLength(0); i++)
                        {
                            if (arrEmps[i, 0] == null) { }
                            else
                            {
                                Console.WriteLine((i + index) + " Name: " + arrEmps[i, 0] + "| Phone:  " + arrEmps[i, 1]);
                            }
                            ;
                        }

                        break;
                    case "l4":
                        Console.WriteLine("Загрузка пользователей из файла 'json.txt', содержащего одого пользователя: ");
                        int index4 = 0;                        
                        Console.WriteLine($"{index4} Name: {currency.Name} | Phone: {currency.Phone}");
                        ++index4;
                        
                    break;
                    case "l2":
                        Console.WriteLine("Загрузка пользователей из json сохранённом в plugin.cs");
                        int indexL2 = 0;
                        foreach (var employee in employeesList2)
                        {
                            Console.WriteLine($"{indexL2} Name: {employee.Name} | Phone: {employee.Phone}");
                            ++indexL2;
                        }
                        break;
                    case "l3":
                        Console.WriteLine("Загрузка пользователей из файла: 'dataJson.json'");
                        int indexL3 = 0;
                        foreach (var employee in currencyDataJson)
                        {
                            Console.WriteLine($"{indexL3} Name: {employee.Name} | Phone: {employee.Phone}");
                            ++indexL3;
                        }
                        break;
                    case "d3":
                        Console.Write("Index of employee to delete: ");
                        int indexToDelete3;
                        if (!Int32.TryParse(Console.ReadLine(), out indexToDelete3))
                        {
                            logger.Error("Not an index or not an int value!");
                        }
                        else
                        {
                            if (indexToDelete3 >= 0 && indexToDelete3 < currencyDataJson.Count())
                            {
                                currencyDataJson.RemoveAt(indexToDelete3);
                            }
                        }
                        break;
                    case "d2":
                        Console.Write("Index of employee to delete: ");
                        int indexToDelete2;
                        if (!Int32.TryParse(Console.ReadLine(), out indexToDelete2))
                        {
                            logger.Error("Not an index or not an int value!");
                        }
                        else
                        {
                            if (indexToDelete2 >= 0 && indexToDelete2 < employeesList2.Count())
                            {
                                employeesList2.RemoveAt(indexToDelete2);
                            }
                        }
                        break;
                    case "a2":
                        Console.Write("Name: >>");
                        string name2 = Console.ReadLine();
                        Console.Write("Phone: ");
                        string phone2 = Console.ReadLine();
                        EmployeesDTO nextE2 = new EmployeesDTO();
                        nextE2.Name = name2;
                        if (String.IsNullOrEmpty(phone2)) 
                        {
                            phone2 = "-";
                        };  
                        nextE2.AddPhone(phone2);
                        employeesList2.Add(nextE2);
                        Console.WriteLine($"{name2} added to employees");
                        break;
                    case "add":
                        Console.Write("Name: >>");
                        string name = Console.ReadLine();
                        Console.Write("Phone: ");
                        string phone = Console.ReadLine();
                        EmployeesDTO nextE = new EmployeesDTO();
                        nextE.Name = name;
                        nextE.AddPhone(phone);
                        employeesList.Add(nextE);
                        Console.WriteLine($"{name} added to employees");
                        break;
                    //case "json":

                    //    nextEJson.Name = "nameTemp";
                    //    nextEJson.Name = null;
                    //    nextEJson.Name = "nameTemp1";
                    //    nextEJson.Name = "nameTemp2";
                    //    nextEJson.AddPhone("phoneTemp");


                    //    var fileJson = "{\r\n      \"id\": 1,\r\n      \"Name\": \"Emily\",\r\n      \"lastName\": \"Johnson\",\r\n      \"maidenName\": \"Smith\",\r\n      \"age\": 28,\r\n      \"gender\": \"female\",\r\n      \"email\": \"emily.johnson@x.dummyjson.com\",\r\n      \"phone\": \"+81 965-431-3024\",\r\n      \"username\": \"emilys\",\r\n      \"password\": \"emilyspass\",\r\n      \"birthDate\": \"1996-5-30\",\r\n      \"image\": \"https://dummyjson.com/icon/emilys/128\",\r\n      \"bloodGroup\": \"O-\",\r\n      \"height\": 193.24,\r\n      \"weight\": 63.16,\r\n      \"eyeColor\": \"Green\",\r\n      \"hair\": {\r\n        \"color\": \"Brown\",\r\n        \"type\": \"Curly\"\r\n      },\r\n      \"ip\": \"42.48.100.32\",\r\n      \"address\": {\r\n        \"address\": \"626 Main Street\",\r\n        \"city\": \"Phoenix\",\r\n        \"state\": \"Mississippi\",\r\n        \"stateCode\": \"MS\",\r\n        \"postalCode\": \"29112\",\r\n        \"coordinates\": {\r\n          \"lat\": -77.16213,\r\n          \"lng\": -92.084824\r\n        },\r\n        \"country\": \"United States\"\r\n      },\r\n      \"macAddress\": \"47:fa:41:18:ec:eb\",\r\n      \"university\": \"University of Wisconsin--Madison\",\r\n      \"bank\": {\r\n        \"cardExpire\": \"03/26\",\r\n        \"cardNumber\": \"9289760655481815\",\r\n        \"cardType\": \"Elo\",\r\n        \"currency\": \"CNY\",\r\n        \"iban\": \"YPUXISOBI7TTHPK2BR3HAIXL\"\r\n      },\r\n      \"company\": {\r\n        \"department\": \"Engineering\",\r\n        \"name\": \"Dooley, Kozey and Cronin\",\r\n        \"title\": \"Sales Manager\",\r\n        \"address\": {\r\n          \"address\": \"263 Tenth Street\",\r\n          \"city\": \"San Francisco\",\r\n          \"state\": \"Wisconsin\",\r\n          \"stateCode\": \"WI\",\r\n          \"postalCode\": \"37657\",\r\n          \"coordinates\": {\r\n            \"lat\": 71.814525,\r\n            \"lng\": -161.150263\r\n          },\r\n          \"country\": \"United States\"\r\n        }\r\n      },\r\n      \"ein\": \"977-175\",\r\n      \"ssn\": \"900-590-289\",\r\n      \"userAgent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\",\r\n      \"crypto\": {\r\n        \"coin\": \"Bitcoin\",\r\n        \"wallet\": \"0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a\",\r\n        \"network\": \"Ethereum (ERC20)\"\r\n      },\r\n      \"role\": \"admin\"\r\n    }";



                    //    Console.WriteLine("nextEJson:");
                    //    Console.WriteLine(nextEJson.ToJson());
                    //    Console.WriteLine("-----------------");
                    //    Console.WriteLine("-----------------");
                    //    Console.WriteLine("fileJson");
                    //    Console.WriteLine(fileJson);
                    //    employeesList.Add(nextEJson);
                    //    //employeesList.Add(nextEJson);
                    //    Console.WriteLine("nextEJson пользователи загружены: 1 - nameTemp2, phoneTemp");

                    //    break;
                    case "f":
                        int indexLj = 0;
                        //int indexListTemporaryDto = 0;
                        Console.WriteLine("Загрузка новых пользвателей из файлов .json :");
                        foreach (var employee in jsonFiles)
                        {
                            Console.WriteLine(employee);                            
                            
                            var jsonDataJsonL = File.ReadAllText(employee);
                            var currencyDataJsonL = Newtonsoft.Json.JsonConvert.DeserializeObject<List<EmployeesDTO>>(jsonDataJsonL);
                            
                            foreach (var i in currencyDataJsonL)
                            {
                                Console.WriteLine($"{indexLj} Name: {i.Name} | Phone: {i.Phone}");
                                listTemporaryDto.Add(i);
                                ++indexLj;
                            }
                        }

                        break;
                    case "fl":
                        Console.WriteLine("Печать пользователей из всех загруженных файлов .json:");
                        int indexListTemporaryDto = 0;
                        foreach (var employee in listTemporaryDto)
                        {
                            Console.WriteLine($"{indexListTemporaryDto} Name: {employee.Name} | Phone: {employee.Phone}");
                            indexListTemporaryDto++;
                        }
                        break;
                    case "fd":
                        Console.Write("Index of employee to delete: ");
                        int indexToDeleteJ;
                        if (!Int32.TryParse(Console.ReadLine(), out indexToDeleteJ))
                        {
                            logger.Error("Not an index or not an int value!");
                        }
                        else
                        {
                            if (indexToDeleteJ >= 0 && indexToDeleteJ < listTemporaryDto.Count())
                            {
                                listTemporaryDto.RemoveAt(indexToDeleteJ);
                            }
                        }
                        break;
                    case "fa":
                        Console.Write("Name: >>");
                        string nameFa = Console.ReadLine();
                        Console.Write("Phone: ");
                        string phoneFa = Console.ReadLine();
                        EmployeesDTO nextFa = new EmployeesDTO();
                        nextFa.Name = nameFa;
                        nextFa.AddPhone(phoneFa);
                        listTemporaryDto.Add(nextFa);
                        Console.WriteLine($"{nameFa} added to employees");
                        break;
                    case "del":
                        Console.Write("Index of employee to delete: ");
                        int indexToDelete;
                        if (!Int32.TryParse(Console.ReadLine(), out indexToDelete))
                        {
                            logger.Error("Not an index or not an int value!");
                        }
                        else
                        {
                            if (indexToDelete >= 0 && indexToDelete < employeesList.Count())
                            {
                                employeesList.RemoveAt(indexToDelete);
                            }
                        }
                        break;
                }

                Console.WriteLine("");
            }

            return employeesList.Cast<DataTransferObject>();
        }
    }
}
